-- AlterTable
ALTER TABLE "Tournament" ADD COLUMN     "auctionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "registrationDeadline" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
