-- CreateTable
CREATE TABLE "MonthlyBudget" (
    "id" TEXT NOT NULL,
    "jan" INTEGER NOT NULL DEFAULT 50000,
    "feb" INTEGER NOT NULL DEFAULT 50000,
    "mar" INTEGER NOT NULL DEFAULT 50000,
    "apr" INTEGER NOT NULL DEFAULT 50000,
    "may" INTEGER NOT NULL DEFAULT 50000,
    "jun" INTEGER NOT NULL DEFAULT 50000,
    "jul" INTEGER NOT NULL DEFAULT 50000,
    "aug" INTEGER NOT NULL DEFAULT 50000,
    "sep" INTEGER NOT NULL DEFAULT 50000,
    "oct" INTEGER NOT NULL DEFAULT 50000,
    "nov" INTEGER NOT NULL DEFAULT 50000,
    "dec" INTEGER NOT NULL DEFAULT 50000,

    CONSTRAINT "MonthlyBudget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MonthlyExpense" (
    "id" TEXT NOT NULL,
    "jan" INTEGER NOT NULL DEFAULT 25000,
    "feb" INTEGER NOT NULL DEFAULT 25000,
    "mar" INTEGER NOT NULL DEFAULT 25000,
    "apr" INTEGER NOT NULL DEFAULT 25000,
    "may" INTEGER NOT NULL DEFAULT 25000,
    "jun" INTEGER NOT NULL DEFAULT 25000,
    "jul" INTEGER NOT NULL DEFAULT 25000,
    "aug" INTEGER NOT NULL DEFAULT 25000,
    "sep" INTEGER NOT NULL DEFAULT 25000,
    "oct" INTEGER NOT NULL DEFAULT 25000,
    "nov" INTEGER NOT NULL DEFAULT 25000,
    "dec" INTEGER NOT NULL DEFAULT 25000,

    CONSTRAINT "MonthlyExpense_pkey" PRIMARY KEY ("id")
);
